# Rustfmt configuration for 3DNgin

# Edition
edition = "2024"

# Formatting options
max_width = 100
tab_spaces = 4
newline_style = "Unix"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Functions
fn_single_line = false
fn_params_layout = "Tall"
brace_style = "SameLineWhere"

# Structs and enums
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

# Control flow
control_brace_style = "AlwaysSameLine"
indent_style = "Block"

# Comments and documentation
comment_width = 80
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Misc
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
condense_wildcard_suffixes = true

# Unstable features (enable if needed)
# merge_derives = true
# imports_layout = "Mixed" 